FROM nginx:alpine

COPY ./nginx/nginx.conf.template /etc/nginx/nginx.conf.template

COPY ./nginx/init.sh /etc/nginx/init.sh

RUN chmod +x /etc/nginx/init.sh

ENTRYPOINT ["/etc/nginx/init.sh"]

WORKDIR /var/www/public

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]